CREATE TABLE IF NOT EXISTS HWKGROUPS (
    "GROUPID" INTEGER,
    "IDENT" TEXT
);

CREATE TABLE IF NOT EXISTS RELEASE (
    "RELEASE_ID" TEXT,
    "RELEASE_DATE" TEXT,
    "DESCRIPTION" TEXT,
    "VERSION" REAL
);

CREATE TABLE IF NOT EXISTS SECVERSION (
    "VERSION" TEXT,
    "FREESHOTS" INTEGER
);

CREATE TABLE IF NOT EXISTS TSECCODE (
    "CARLINE" TEXT,
    "MODELYEAR" TEXT,
    "PLANT" TEXT,
    "CHASSIS" TEXT,
    "GROUPID" INTEGER,
    "SECCODE_IMMO" TEXT,
    "SECCODE_INFO" TEXT
);

